// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FactoryPocketPro",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Factory Pocket Pro 👑",
            targets: ["AppModule"],
            bundleIdentifier: "com.anass.FactoryPocketPro",
            teamIdentifier: "238BLT527D",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIconNew"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ],
            appCategory: .business
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources",
            resources: [
                .copy("../Backend")
            ]
        )
    ]
)